// Generated by CoffeeScript 1.7.1
(function() {
  var Family, Specific, Summary, fm, r;

  Family = (function() {
    function Family(family) {
      this.family = family;
      this.showMenu = false;
      this.familys = {
        'OSA': {
          operations: ["OSA", "OSA10GB", "OSA2-5GB", "OSA-COC", "OSACRTDV"]
        },
        'L2K': {
          operations: ['EML', 'DML']
        },
        'PIC-DIAMOND': {
          operations: ['PIC-DIAMOND']
        },
        'PIC-PMQP': {
          operations: ['PIC-PMQP']
        },
        'PIC-LR4': {
          operations: ['PIC-LR4']
        },
        'PIC-CFP': {
          operations: ['PIC-CFP']
        },
        'ENG10GTO': {
          operations: ['ENG10GTO']
        },
        'ENG2-5GT': {
          operations: ['ENG2-5GT']
        },
        'ENG10GRO': {
          operations: ['ENG10GRO']
        },
        'TUN': {
          operations: ['TUN']
        }
      };
      this.constructFamilyIndex();
    }

    Family.prototype.constructFamilyIndex = function() {
      return this.index = _.keys(this.familys);
    };

    Family.prototype.switchFamily = function(family) {
      this.family = family;
      r.data.summary = [];
      r.data.specific = {};
      this.familys[this.family].operations.map((function(_this) {
        return function(el) {
          return r.data.summary.push(new Summary(el));
        };
      })(this));
      r.data.show = 'summary';
      return r.data.fm.showMenu = false;
    };

    return Family;

  })();

  Summary = (function() {
    function Summary(family) {
      this.family = family;
      this.data = [];
      this.get();
    }

    Summary.prototype.get = function() {
      var prm;
      NProgress.start();
      return prm = $.getJSON('toolbox.php', {
        action: 'getSummary',
        family: this.family
      }).done((function(_this) {
        return function(data) {
          _this.data = data;
          NProgress.done();
          return r.update();
        };
      })(this));
    };

    return Summary;

  })();

  Specific = (function() {
    function Specific(family, operation) {
      this.family = family;
      this.operation = operation != null ? operation : '';
      this.data = [];
      this.get();
    }

    Specific.prototype.get = function() {
      var prm;
      NProgress.start();
      return prm = $.getJSON('toolbox.php', {
        action: 'getSpecific',
        family: this.family
      }).done((function(_this) {
        return function(data) {
          _this.data = data;
          _this.createHeader();
          _this.filter(_this.operation);
          return NProgress.done();
        };
      })(this));
    };

    Specific.prototype.createHeader = function() {
      return this.header = _.uniq(_.pluck(this.data, 'OPN_CODE'));
    };

    Specific.prototype.filter = function(operation) {
      this.operation = operation != null ? operation : '';
      if (this.operation === '') {
        this.filtered = this.data;
      } else {
        this.filtered = _.filter(this.data, (function(_this) {
          return function(el) {
            return el.OPN_CODE === _this.operation;
          };
        })(this));
      }
      return r.update();
    };

    return Specific;

  })();

  fm = new Family('OSA');

  r = new Ractive({
    el: 'container',
    template: '#template',
    data: {
      fm: fm,
      summary: [new Summary('OSA'), new Summary('OSA10GB'), new Summary('OSA2-5GB'), new Summary('OSA-COC'), new Summary('OSACRTDV')],
      specific: {},
      meta: {
        specific: {
          selected: 'OSACRTDV',
          family: ''
        }
      },
      show: 'summary',
      justName: function(fullName) {
        return fullName.match(/\w*/);
      }
    }
  });

  r.on('familyDetail', function(e, val) {
    var family;
    e.original.preventDefault();
    family = r.data.summary[e.keypath.match(/\w*\.(\d+)/i)[1]].family;
    if (r.data.specific[family] == null) {
      r.data.specific[family] = new Specific(family);
      r.set('meta.specific.selected', family);
    } else {
      r.data.specific[family].filter('');
      r.set('meta.specific.selected', family);
    }
    return r.set('show', 'specific');
  });

  r.on('CodeDetail', function(e, val) {
    var c, d, f, family, operation, _ref;
    e.original.preventDefault();
    _ref = e.keypath.match(/\w*\.(\d+)\.\w+\.(\d+)/i), d = _ref[0], f = _ref[1], c = _ref[2];
    family = r.data.summary[f].family;
    operation = r.data.summary[f].data[c].OPN_CODE;
    console.log([family, operation]);
    if (r.data.specific[family] == null) {
      r.data.specific[family] = new Specific(family, operation);
      r.set('meta.specific.selected', family);
    } else {
      r.data.specific[family].filter(operation);
      r.set('meta.specific.selected', family);
    }
    return r.set('show', 'specific');
  });

  r.on('unfilter', function(e) {
    e.original.preventDefault();
    return r.data.specific[r.data.meta.specific.selected].filter('');
  });

  r.on('filter', function(e, operation) {
    e.original.preventDefault();
    return r.data.specific[r.data.meta.specific.selected].filter(operation);
  });

  r.on('show', function(e, element) {
    e.original.preventDefault();
    return r.set('show', element);
  });

  r.on('toggleFamily', function(e) {
    e.original.preventDefault();
    r.set('fm.showMenu', !r.data.fm.showMenu);
    return console.log(r.data.fm.showMenu);
  });

  r.on('selectFamily', function(e, fam) {
    e.original.preventDefault();
    console.log(fam);
    return r.data.fm.switchFamily(fam);
  });

  window.r = r;

}).call(this);

//# sourceMappingURL=app.map
