// Generated by CoffeeScript 1.7.1
(function() {
  var Piece, Tag, r;

  Tag = (function() {
    function Tag(id) {
      this.id = id;
      this.scanned = [];
      this.fromDB = [];
      this.getFromDatabase();
      this.labelColor = '';
      this.loadingIcon = true;
    }

    Tag.prototype.getFromDatabase = function() {
      var coneccion;
      return coneccion = $.getJSON('toolbox.php', {
        action: 'getLPN',
        lpn: this.id
      }).done((function(_this) {
        return function(data) {
          _this.fromDB = data;
          _this.labelColor = 'green';
          return r.update();
        };
      })(this)).fail((function(_this) {
        return function(err) {
          return _this.labelColor = 'red';
        };
      })(this));
    };

    return Tag;

  })();

  Piece = (function() {
    function Piece(id, source) {
      this.id = id;
      this.source = source;
      this.data = [];
    }

    Piece.prototype.isFromScan = function() {
      if (this.source = 'scan') {
        return true;
      }
    };

    return Piece;

  })();

  r = new Ractive({
    el: 'container',
    template: '#template',
    data: {
      serial_num: '',
      show: 'byTag',
      scan: '',
      tags: []
    }
  });

  r.on('getScanner', function(e, val) {
    e.original.preventDefault();
    if (/MX\d{8}/.test(r.data.scan)) {
      console.log(r.data.scan);
      r.data.tags.unshift(new Tag(r.data.scan));
      return r.set('scan', '');
    }
  });

  r.on('selectTag', function(e, tagId) {
    e.original.preventDefault();
    r.set('selectedTag', tagId);
    return r.set('scan', tagId);
  });

  window.r = r;

}).call(this);

//# sourceMappingURL=main.map
