// Generated by CoffeeScript 1.7.1
(function() {
  var r, series;

  series = [];

  r = new Ractive({
    el: 'container',
    template: '#template',
    data: {
      serial_num: '',
      show: 'byTag',
      scan: '',
      lpn: []
    }
  });

  r.on('getScanner', function(e, val) {
    e.original.preventDefault();
    console.log(r.data.scan);
    return r.set('scan', '');
  });

  window.r = r;

}).call(this);

//# sourceMappingURL=main.map
